/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException; 
import java.io.File;
import java.io.FileOutputStream;
import java.text.MessageFormat;
import javax.swing.JTable;

/**
 *
 * @author Alma
 */
public class ReporteProyecto extends javax.swing.JFrame {

    /**
     * Creates new form ReporteProyecto
     */
    public ReporteProyecto() {
        initComponents();
        Mostrardatos();
         fech.setEnabled(false);
    }

    ReporteProyecto(Principal aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
     void Mostrardatos(){
        

 DefaultTableModel modelo = new DefaultTableModel();
  
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Estrategia");
        modelo.addColumn("Inicio");
        modelo.addColumn("Final");
        modelo.addColumn("Duracion");
        modelo.addColumn("Monto individual");
        modelo.addColumn("Monto Total");
        modelo.addColumn("Financiamiento 1");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Financiamiento 2");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Insttucion");
      

        tblproyecto.setModel(modelo);
    

        String sql="";
        
            sql="SELECT * FROM proyecto ORDER BY fecha_inicio ASC";
       

        String[] datos= new String[15];
        try {
            Statement at= reg.createStatement();
            ResultSet rs= at.executeQuery(sql);
            while(rs.next()){
                  datos[0]=rs.getString(2);
                datos[1]=rs.getString(3);
                datos[2]= rs.getString(4);
                datos[3]=rs.getString(5);
                datos[4]=rs.getString(6);
                datos[5]=rs.getString(7);
                datos[6]=rs.getString(8);
                datos[7]=rs.getString(9);
                datos[8]=rs.getString(10);
                datos[9]=rs.getString(11);
                datos[10]=rs.getString(12);
                datos[11]=rs.getString(13);
                datos[12]=rs.getString(14);
                
                


                modelo.addRow(datos);
            }

            tblproyecto.setModel(modelo);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ReporteActFestiva.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
    }     

     
      void enviar(){
String dia = Integer.toString(txtfecha.getCalendar().get(Calendar.DAY_OF_MONTH));
String mes = Integer.toString(txtfecha.getCalendar().get(Calendar.MONTH) + 1);
String year = Integer.toString(txtfecha.getCalendar().get(Calendar.YEAR));
String fecha = (year + "/"+  mes +"/" + dia);
fech.setText(fecha);       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtfecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtdur = new javax.swing.JTextField();
        btname = new javax.swing.JButton();
        btfech = new javax.swing.JButton();
        btdur = new javax.swing.JButton();
        fech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblproyecto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel1.setText("Nombre del Proyecto");

        jLabel2.setText("Fecha de inicio");

        jLabel3.setText("Duracion");

        txtdur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurActionPerformed(evt);
            }
        });

        btname.setIcon(new javax.swing.ImageIcon("/Users/gtk1x/Desktop/gromm/Search-48.png")); // NOI18N
        btname.setText("Ver");
        btname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnameActionPerformed(evt);
            }
        });

        btfech.setIcon(new javax.swing.ImageIcon("/Users/gtk1x/Desktop/gromm/Search-48.png")); // NOI18N
        btfech.setText("Ver");
        btfech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfechActionPerformed(evt);
            }
        });

        btdur.setIcon(new javax.swing.ImageIcon("/Users/gtk1x/Desktop/gromm/Search-48.png")); // NOI18N
        btdur.setText("Ver");
        btdur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdurActionPerformed(evt);
            }
        });

        fech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("/Users/gtk1x/Desktop/gromm/Document-50.png")); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("/Users/gtk1x/Desktop/gromm/Minus-48.png")); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("/Users/gtk1x/Desktop/gromm/Toolbox-48.png")); // NOI18N
        jButton3.setText("Ver todos los Proyectos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdur))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btdur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btname)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btfech)
                            .addGap(18, 18, 18)
                            .addComponent(fech, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103)
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btfech)
                        .addComponent(fech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btdur)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblproyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproyectoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblproyecto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurActionPerformed

    private void fechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechActionPerformed

    private void tblproyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproyectoMouseClicked
     
    }//GEN-LAST:event_tblproyectoMouseClicked

    private void btnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnameActionPerformed

 DefaultTableModel modelo = new DefaultTableModel();
  
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Estrategia");
        modelo.addColumn("Inicio");
        modelo.addColumn("Final");
        modelo.addColumn("Duracion");
        modelo.addColumn("Monto individual");
        modelo.addColumn("Monto Total");
        modelo.addColumn("Financiamiento 1");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Financiamiento 2");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Institucion");
      

        tblproyecto.setModel(modelo);
        String nom= txtname.getText();
    

        String sql="";
        
            sql= "SELECT * FROM proyecto WHERE nombre='"+nom+"'";
       

        String[] datos= new String[15];
        try {
            Statement at= reg.createStatement();
            ResultSet rs= at.executeQuery(sql);
            while(rs.next()){
                  datos[0]=rs.getString(2);
                datos[1]=rs.getString(3);
                datos[2]= rs.getString(4);
                datos[3]=rs.getString(5);
                datos[4]=rs.getString(6);
                datos[5]=rs.getString(7);
                datos[6]=rs.getString(8);
                datos[7]=rs.getString(9);
                datos[8]=rs.getString(10);
                datos[9]=rs.getString(11);
                datos[10]=rs.getString(12);
                datos[11]=rs.getString(13);
                datos[12]=rs.getString(14);
                
                


                modelo.addRow(datos);
            }

            tblproyecto.setModel(modelo);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ReporteActFestiva.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 
    MessageFormat header= new MessageFormat("Reporte Proyecto");
    tblproyecto.print(JTable.PrintMode.FIT_WIDTH, header, header);
}    catch (PrinterException ex) { 
} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Mostrardatos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdurActionPerformed


 DefaultTableModel modelo = new DefaultTableModel();
  
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Estrategia");
        modelo.addColumn("Inicio");
        modelo.addColumn("Final");
        modelo.addColumn("Duracion");
        modelo.addColumn("Monto individual");
        modelo.addColumn("Monto Total");
        modelo.addColumn("Financiamiento 1");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Financiamiento 2");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Institucion");
      

        tblproyecto.setModel(modelo);
        String dura= txtdur.getText();
    

        String sql="";
        
            sql= "SELECT * FROM proyecto WHERE duracion='"+dura+"'";
       

        String[] datos= new String[15];
        try {
            Statement at= reg.createStatement();
            ResultSet rs= at.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(2);
                datos[1]=rs.getString(3);
                datos[2]= rs.getString(4);
                datos[3]=rs.getString(5);
                datos[4]=rs.getString(6);
                datos[5]=rs.getString(7);
                datos[6]=rs.getString(8);
                datos[7]=rs.getString(9);
                datos[8]=rs.getString(10);
                datos[9]=rs.getString(11);
                datos[10]=rs.getString(12);
                datos[11]=rs.getString(13);
                datos[12]=rs.getString(14);
                
                


                modelo.addRow(datos);
            }

            tblproyecto.setModel(modelo);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ReporteActFestiva.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btdurActionPerformed

    private void btfechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfechActionPerformed
        enviar();
         
         DefaultTableModel modelo = new DefaultTableModel();
         
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Estrategia");
        modelo.addColumn("Inicio");
        modelo.addColumn("Final");
        modelo.addColumn("Duracion");
        modelo.addColumn("Monto individual");
        modelo.addColumn("Monto Total");
        modelo.addColumn("Financiamiento 1");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Financiamiento 2");
        modelo.addColumn("Porcentaje");
        modelo.addColumn("Institucion");
      

        tblproyecto.setModel(modelo);
         String fecha = fech.getText();
         
          String sql="";
        if(fecha.equals(""))
        {
            sql="SELECT * FROM proyecto";
        }
        else{
            sql="SELECT * FROM proyecto WHERE fecha_inicio='"+fecha+"'";
            
        }
         String[] datos= new String[15];
        try {
            Statement at= reg.createStatement();
            ResultSet rs= at.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(2);
                datos[1]=rs.getString(3);
                datos[2]= rs.getString(4);
                datos[3]=rs.getString(5);
                datos[4]=rs.getString(6);
                datos[5]=rs.getString(7);
                datos[6]=rs.getString(8);
                datos[7]=rs.getString(9);
                datos[8]=rs.getString(10);
                datos[9]=rs.getString(11);
                datos[10]=rs.getString(12);
                datos[11]=rs.getString(13);
                datos[12]=rs.getString(14);
                
                


                modelo.addRow(datos);
            }

            tblproyecto.setModel(modelo);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ReporteActFestiva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btfechActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdur;
    private javax.swing.JButton btfech;
    private javax.swing.JButton btname;
    private javax.swing.JTextField fech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblproyecto;
    private javax.swing.JTextField txtdur;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
Conexion con=new Conexion();
Connection reg = con.conexion();

}
